name: Run Shell Script

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image '
        required: true
        default: 'https://sourceforge.net/projects/andyyan-gsi/files/lineage-19.x/lineage-19.1-20230715-UNOFFICIAL-a64_bgN.img.xz'        
      ARCH:
        description: 'Arm32 or Arm64'
        required: true
        default: '32'                
      NAME:
        description: 'Rom Name'
        required: true
        default: 'LineageOS_19.1_SDM439_ARM32_Gapps'                

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget

    - name: Preparing Files
      run: |
        echo "Preparing Files" 
        wget -q -P "./temp" ${{ github.event.inputs.GSI }}        
        wget -q https://sourceforge.net/projects/samsung-galaxy-a01-m01/files/custom_rom_builder_439.zip
        echo "Unziping Files"        
        unzip custom_rom_builder_439.zip
        rm -r custom_rom_builder_439.zip

    - name: Downloading your Gsi
      run: |
        echo "Downloading your Gsi"        
        wget -q -P "./temp" ${{ github.event.inputs.GSI }} 
        echo "Setting Permissions"               
        chmod 755 *
        chmod 755 ./bin/*
        ./arm${{ github.event.inputs.ARCH }}_git        

    - name: Building
      run: |
        ./arm${{ github.event.inputs.ARCH }}_git        

    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.NAME }}   # Replace with a suitable name
        path: ./zip/Custom_Rom_SDM439.zip
